export const GET_USER = 'GET_USER'
export const GET_USER_PENDING = 'GET_USER_PENDING'
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED'
export const GET_USER_REJECTED = 'GET_USER_REJECTED'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_FULFILLED = 'LOGOUT_USER_FULFILLED'
export const LOGOUT_USER_REJECTED = 'LOGOUT_USER_REJECTED'

